DROP TABLE VOCAB_ADMIN.LANGUAGE;

CREATE TABLE VOCAB_ADMIN.LANGUAGE (
  LANG_ID NUMBER  NOT NULL,
  LANG_NAME VARCHAR2(256) NOT NULL,
  LANG_SHORTCUT VARCHAR2(256) UNIQUE,
  CONSTRAINT LANGUAGE_PK PRIMARY KEY (LANG_ID)
);

CREATE TABLE VOCAB_ADMIN.WORD (
  WORD_ID NUMBER NOT NULL,
  WORD_TEXT VARCHAR2(1024) NOT NULL,
  WORD_LANG_ID NUMBER NOT NULL,
  CONSTRAINT WORD_PK PRIMARY KEY (WORD_ID),
  CONSTRAINT WORD_LANG_FK FOREIGN KEY (WORD_LANG_ID) REFERENCES VOCAB_ADMIN.LANGUAGE(LANG_ID)
);
